namespace HungryMonster.Core.Entities;

/// <summary>
/// Abstract base class for all entity types. Provides identity and audit fields.
/// All state changes must go through the entity's own methods — no public setters.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>Primary key, generated by the database.</summary>
    public int Id { get; private set; }

    /// <summary>UTC timestamp set when the entity is first created.</summary>
    public DateTime CreatedAt { get; private set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp updated whenever a domain method mutates the entity. Null until first update.</summary>
    public DateTime? UpdatedAt { get; private set; }

    /// <summary>Called by derived classes to stamp the last-modified time.</summary>
    protected void SetUpdatedAt() => UpdatedAt = DateTime.UtcNow;
}
